---

- name: Create Group
  group:
    name: "{{zookeeper.group}}"
    state: present

- name: Create User
  user:
    name: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
    state: present

- name: Download Zookeeper
  get_url:
    url: http://mirror.csclub.uwaterloo.ca/apache/zookeeper/zookeeper-{{zookeeper.version}}/zookeeper-{{zookeeper.version}}.tar.gz
    dest: /tmp/zookeeper-{{zookeeper.version}}.tar.gz

- name: Extract Zookeeper
  unarchive:
    src: /tmp/zookeeper-{{zookeeper.version}}.tar.gz
    dest: /opt/
    copy: no

- name: Remove Existing Install
  command: rm -rf "{{ zookeeper.dir }}"

- name: Move Zookeeper Install Directory
  command: mv -f /opt/zookeeper-{{zookeeper.version}} "{{ zookeeper.dir }}"

- name: Create Data Directory
  file:
    path: "{{zookeeper.data_dir}}"
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
    mode: 0755
    state: directory

- name: Create Log Directory
  file:
    path: "{{zookeeper.log_dir}}"
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
    mode: 0755
    state: directory

- name: Update Permissions
  file:
    path: "{{ zookeeper.dir }}"
    owner: "{{ zookeeper.user }}"
    group: "{{ zookeeper.group }}"
    recurse: yes
    mode: 0755
    state: directory
