---

- name: reload supervisor
  shell: supervisorctl reload
  when: ansible_distribution == 'Ubuntu'

- name: reload supervisor
  shell: /usr/local/bin/supervisorctl reload
  when: ansible_distribution == 'Amazon'

- name: restart supervisor
  service:
    name: supervisord
    state: restarted
