---

#Using pip to install supervisor on amazon as the rpm is from 2007
- name: install supervisor amazon
  pip:
    name: supervisor

- name: ensure supervisor conf.d directory exists
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: ensure supervisor log directory exists
  file:
    path: /var/log/supervisor
    state: directory

- name: Copy supervisor global configuration
  copy:
    src: supervisord.conf
    dest: /etc/supervisor/supervisord.conf
    mode: 0644
    owner: root
  notify:
    - reload supervisor

- name: Install as service with automatic start on amazon
  copy:
    src: supervisor-amazon
    dest: /etc/rc.d/init.d/supervisord
    mode: 0755
    group: root
    owner: root

- name: Enable and run service
  service:
    name: supervisord
    state: started
    enabled: yes
