---

- name: install supervisor debian/ubuntu
  apt:
    pkg: supervisor
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: ensure supervisor conf.d directory exists
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: ensure supervisor log directory exists
  file:
    path: /var/log/supervisor
    state: directory

- name: Copy supervisor global configuration
  copy:
    src: supervisord.conf
    dest: /etc/supervisord.conf
  notify:
    - reload supervisor

- name: Enable and run service
  service:
    name: supervisor
    state: started
    enabled: yes
