---

- name: Ensure there is no .aws directory as exhibitor doesn't love it.
  file:
    path: /root/.aws
    state: absent

- name: Create Group
  group:
    name: "{{exhibitor.group}}"
    state: present

- name: Create User
  user:
    name: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    state: present

- name: Create Directory
  file:
    path: "{{exhibitor.dir}}"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    mode: 0755
    state: directory

- name: Create Data Directory
  file:
    path: "{{exhibitor.data_dir}}"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    mode: 0755
    state: directory

- name: Create Config Directory
  file:
    path: "{{exhibitor.config_dir}}"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    mode: 0755
    state: directory

- name: Download Exhibitor JAR
  command: >
    aws s3 cp s3://{{ exhibitor.s3_bucket_resources }}/exhibitor-1.5.6.jar {{playbook_dir}}/roles/{{role_path|basename}}/files/

- name: Copy Exhibitor JAR
  copy:
    src: "exhibitor-{{exhibitor.version}}.jar"
    dest: "{{exhibitor.dir}}/exhibitor.jar"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"

- name: Set exhibitor.cfg
  template:
    src: exhibitor.cfg.j2
    dest: "{{ exhibitor.dir }}/exhibitor.cfg"
    owner: "{{ exhibitor.user }}"
    group: "{{ exhibitor.group }}"
    mode: 0755

- name: Update Permissions
  file:
    path: "{{ exhibitor.dir }}"
    owner: "{{ exhibitor.user }}"
    group: "{{ exhibitor.group }}"
    recurse: yes
    mode: 0755
    state: directory

- name: Add supervisor config
  template:
    src: supervisor.exhibitor.conf.j2
    dest: /etc/supervisor/conf.d/exhibitor.conf
    owner: "{{ exhibitor.user }}"
    group: "{{ exhibitor.group }}"
    mode: 0644
  notify:
    - restart supervisor
